### ISSUE TITLE
Rajouter Mocha et faire quelques tests simples

### ISSUE THREAD

**Issue by DavidBruant** [DavidBruant/bouture#1]

**Comment by pointbar** [comment]
Style TDD - µ-test, code, µ-test, code, ... - ?
Ou écrire quelques tests puis coder, plus dans un style BDD ?

**Comment by DavidBruant** [comment]
Je dévie un peu du sujet pour faire une proposition de manière de fonctionner : 
je créé une PR avec des tests (2-3, jamais plus) et tu écris le code qui implémente ?

Je cherche une manière d'interagir qui maximise l'apprentissage et j'ai du mal à juger si cette proposition fait du mal à ce but

**Comment by pointbar** [comment]
Oui, ça se tente, à donf

**Comment by DavidBruant** [comment]
Closed by #7
