### ISSUE TITLE
Rajouter ESLint

### ISSUE THREAD

**Issue by DavidBruant** [DavidBruant/bouture#2]
Premère config : https://github.com/datalocale/dataviz-finances-gironde/blob/master/.eslintrc.yml

**Comment by pointbar** [comment]
J'avais pas vu cette issue, est-ce que je remplace -standard- par cette config ?

**Comment by DavidBruant** [comment]
tkt. On n'a qu'à dire que c'est bon. On ajustera plus tard. La présence d'ESLint me suffit à ce stade
