### ISSUE TITLE
Rajouter Travis CI avec chrome ou firefox headless

### ISSUE THREAD

**Issue by DavidBruant** [DavidBruant/bouture#3]
https://docs.travis-ci.com/user/gui-and-headless-browsers/#Using-the-Chrome-addon-in-the-headless-mode

https://docs.travis-ci.com/user/gui-and-headless-browsers/#Using-the-Firefox-addon-in-headless-mode

**Comment by pointbar** [comment]
Je passe un peu de temps là-dessus, et j'apprends plein de trucs.

**Comment by DavidBruant** [comment]
👍 :-)
